"""corpus-capture: publisher profiles, figure selection, and the intake contract.

The browser extension in ``extension/`` is the producer. This package is what a
RECEIVER needs: the same publisher registry the extension fetches, the same
structural figure selection, and the sidecar contract both sides emit. Sharing
the code is the point -- a receiver that reimplements the selectors drifts from
the extension, and the copy that drifts silently is the one nobody runs by hand.
"""

from corpus_capture.figure_manifest import (
    FigureManifest,
    FigureRecord,
    build_figure_manifest,
    figure_label,
    find_article_container,
    is_decorative_asset,
)
from corpus_capture.profiles import (
    REGISTRY_PATH,
    SCHEMA_VERSION,
    ProfileRegistryError,
    fixture_path,
    load_registry,
    profile_for_url,
    profile_status_table,
    public_registry,
    validate_registry,
)
from corpus_capture.sidecar import (
    ACCESS_CLASSES,
    ATTACHMENT_KINDS,
    ATTACHMENT_STATUSES,
    ATTACHMENT_SUFFIXES,
    MAX_ATTACHMENT_BYTES,
    MAX_ATTACHMENTS,
    PRODUCER_KEY,
    READER_REVIEW_FIELDS,
    REVIEW_DECISIONS,
    REVIEW_METADATA_FIELDS,
    SIDECAR_SCHEMA,
    SIDECAR_SCHEMAS_ACCEPTED,
    SidecarError,
    attachment_payload_name,
    capture_slug,
    download_basename,
    normalize_doi,
    validate_attachment_row,
    validate_attachments,
    validate_reader_review,
    validate_sidecar,
)
from corpus_capture.submission import (
    ALLOWED_FIELDS,
    ATTACHMENT_META_FIELDS,
    FINALIZE_FIELDS,
    FORBIDDEN_FIELDS,
    MAX_BODY_BYTES,
    MAX_HTML_BYTES,
    MAX_METADATA_BYTES,
    ReceiptStore,
    SubmissionError,
    enforce_body_size,
    validate_attachment_meta,
    validate_finalize,
    validate_submission,
)

__version__ = "0.2.0"

__all__ = [
    "ACCESS_CLASSES",
    "ALLOWED_FIELDS",
    "ATTACHMENT_KINDS",
    "ATTACHMENT_META_FIELDS",
    "ATTACHMENT_STATUSES",
    "ATTACHMENT_SUFFIXES",
    "FINALIZE_FIELDS",
    "FORBIDDEN_FIELDS",
    "MAX_ATTACHMENTS",
    "MAX_ATTACHMENT_BYTES",
    "MAX_BODY_BYTES",
    "MAX_HTML_BYTES",
    "MAX_METADATA_BYTES",
    "PRODUCER_KEY",
    "READER_REVIEW_FIELDS",
    "REGISTRY_PATH",
    "REVIEW_DECISIONS",
    "REVIEW_METADATA_FIELDS",
    "SCHEMA_VERSION",
    "SIDECAR_SCHEMA",
    "SIDECAR_SCHEMAS_ACCEPTED",
    "FigureManifest",
    "FigureRecord",
    "ProfileRegistryError",
    "ReceiptStore",
    "SidecarError",
    "SubmissionError",
    "__version__",
    "attachment_payload_name",
    "build_figure_manifest",
    "capture_slug",
    "download_basename",
    "enforce_body_size",
    "figure_label",
    "find_article_container",
    "fixture_path",
    "is_decorative_asset",
    "load_registry",
    "normalize_doi",
    "profile_for_url",
    "profile_status_table",
    "public_registry",
    "validate_attachment_meta",
    "validate_attachment_row",
    "validate_attachments",
    "validate_finalize",
    "validate_reader_review",
    "validate_registry",
    "validate_sidecar",
    "validate_submission",
]
